# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 04:19
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseAnEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title:', max_length=128, unique=True)),
                ('theme', models.CharField(help_text='Event theme:', max_length=128)),
                ('capacity', models.IntegerField(help_text='Guest capacity (maximum:25', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('date', models.DateField(help_text='Event date:')),
                ('start', models.TimeField(help_text='Start time:')),
                ('end', models.TimeField(help_text='End time:')),
                ('organizerusername', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=128)),
                ('mainCourse', models.CharField(max_length=128)),
                ('dessert', models.CharField(max_length=128)),
                ('ident', models.IntegerField(unique=True)),
                ('drink', models.CharField(max_length=128)),
                ('edate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edate', to='bark.Event')),
                ('etime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etime', to='bark.Event')),
                ('etitle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etitle', to='bark.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('starvalue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, default='default/person.jpg', null=True, upload_to='profile_images/')),
                ('dog_picture', models.ImageField(blank=True, default='default/dog.jpg', null=True, upload_to='profile_images/')),
                ('dog_name', models.CharField(max_length=128)),
                ('is_organizer', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('avgrating', models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('events', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='organizername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizername', to='bark.UserProfile'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ownername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to='bark.UserProfile'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='eventdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventdate', to='bark.Event'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='eventtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtitle', to='bark.Event'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='ownerusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerusername', to='bark.UserProfile'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bark.Event'),
        ),
    ]
