# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 02:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseAnEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('theme', models.CharField(max_length=128)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)])),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=128)),
                ('mainCourse', models.CharField(max_length=128)),
                ('dessert', models.CharField(max_length=128)),
                ('ident', models.IntegerField(unique=True)),
                ('drink', models.CharField(max_length=128)),
                ('edate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edate', to='bark.Event')),
                ('etime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etime', to='bark.Event')),
                ('etitle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etitle', to='bark.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starvalue', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ident', models.IntegerField()),
                ('comment', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bark.User')),
                ('dogname', models.CharField(max_length=128)),
            ],
            bases=('bark.user',),
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bark.User')),
                ('avgrating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            bases=('bark.user',),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='eventdate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventdate', to='bark.Event'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='eventtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventtitle', to='bark.Event'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bark.Event'),
        ),
        migrations.AddField(
            model_name='rating',
            name='organizeruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizeruser', to='bark.Organizer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='ownername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownername', to='bark.DogOwner'),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='organizerusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bark.Organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizerusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bark.Organizer'),
        ),
        migrations.AddField(
            model_name='chooseanevent',
            name='ownerusername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerusername', to='bark.DogOwner'),
        ),
    ]
