# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dessert',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='dog_food',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='drink',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='main',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='starter',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
