# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bark', '0002_auto_20180314_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='organizename',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='organizername', to='bark.UserProfile'),
            preserve_default=False,
        ),
    ]
