# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bark', '0003_auto_20180316_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dog_picture',
            field=models.ImageField(blank=True, default='default/dog.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/person.jpg', upload_to='profile_images/'),
        ),
    ]
