# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bark', '0004_auto_20180308_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogowner',
            options={'verbose_name_plural': 'Users/DogOwners'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name_plural': 'Users/Organizers'},
        ),
    ]
