# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 01:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('bark', '0005_auto_20180308_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizerusername',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='organizerusername',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='organizeruser',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(help_text='Guest capacity', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(help_text='End time:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(help_text='Start time:'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(help_text='Event theme:', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title:', max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
